### ISSUE TITLE
createClient missed some arguments

### ISSUE THREAD

**Issue by DmitryShlepkin** [DeuxHuitHuit/google_analytics_dashboard#1]
Symphony 2.6.2
I add Google Analytics panel, provide service account email and absolute path to the p12 key file, and the after save i get next message:

``` php
Symphony Recoverable Error: Argument 1 passed to extension_google_analytics_dashboard::createClient() must be of the type array, boolean given, called in /home/acidbeast/www/new.dimko.org/htdocs/extensions/google_analytics_dashboard/content/content.index.php on line 45 and defined
```

``` php
An error occurred in /home/acidbeast/www/new.dimko.org/htdocs/extensions/google_analytics_dashboard/extension.driver.php around line 186
```

Do i miss something?

<img width="821" alt="screen shot 2015-08-06 at 5 08 20 pm" src="https://cloud.githubusercontent.com/assets/754724/9113533/c9c2c76c-3c5d-11e5-9697-7baa3072fccf.png">

**Comment by nitriques** [comment]
Hum do you run the latest 1.0.1 version ?

Also, do you run the dashboard v2.0 ? I've just created the release: https://github.com/symphonists/dashboard/releases/tag/2.0.0

**Comment by DmitryShlepkin** [comment]
Oh, sorry my dashboard is outdated,
Thanks for extension! It awesome!

**Comment by nitriques** [comment]
My pleasure ! Please keep reporting any bugs :)
